---
title: Service auto Celaru
author: Service auto Celaru
email: serviceautocelaru[at]yahoo.com
description: Service auto Celaru
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
